project:
  type: book
  output-dir: _book
  
lang: de

book:
  title: "Analoge Schaltungstechnik"
  author:
    - name: Mirco Meiners
      orcid: 0000-0002-9709-4191
      email: Mirco.Meiners@hs-bremen.de
      corresponding: true
      roles: "Lead author"
      affiliation:
        - name: Hochschule Bremen - City University of Applied Sciences (HSB)
          city: Bremen
          state: Germany
          url: https://www.hs-bremen.de/person/mimeiners/ 
    - name: Tim Ziemann
      email: Tim.Ziemann@hs-bremen.de
      roles: "Supporting author"
  date: last-modified
  license: "Apache-2.0 license"

  reader-mode: true

  page-footer:
    left: |
      M 6.9 Analoge Schaltungstechnik (ANS), M. Meiners, HSB.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
#  cover-image: images/hsb-logo.png
  favicon: images/hsb-logo.png
  site-url: https://mimeiners.github.io/ans/
  repo-url: https://github.com/mimeiners/ans/
  repo-branch: main
  repo-actions: [edit,issue]
  downloads: [pdf,epub]
    
  chapters:
    - index.qmd
    - part: Seminar
      chapters:
        - lec/lec-01-intro.qmd
        # - lec/lec-02-modelling.qmd
        # - lec/lec-03-cs_amp.qmd
        # - lec/lec-04-op_analysis.qmd
        # - lec/lec-05-gain_and_ro.qmd
        # - lec/lec-06-intrinsic_cap.qmd
        # - lec/lec-07-extrinsic_cap.qmd
        # - lec/lec-08-miller.qmd
        # - lec/lec-09-zvtc.qmd
        # - lec/lec-10-cg_stage.qmd
        # - lec/lec-11-cd_stage.qmd
        # - lec/lec-12-proc_var.qmd
        # - lec/lec-13-mirror.qmd
        # - lec/lec-14-biasing.qmd
        # - lec/lec-15-diff_pair.qmd
        # - lec/lec-16-fb1.qmd
        # - lec/lec-17-fb2.qmd
        # - lec/lec-18a-MCD6thEdChap10.qmd
        # - lec/lec-18b-MCD6thEdChap11.qmd
        # - lec/lec-18c-ota_simple_ic.qmd
        # - lec/lec-18d-ota_design_ic.qmd
        # - lec/lec-18e-ota_behavior_ic.qmd
        # - lec/lec-19-ota_fb_cir_ic.qmd
        # - lec/lec-20-integrators.qmd
        # - lec/lec-21-MCD6thEdChap12.qmd
        - lec/lec-22a-analog_filter_design.qmd
        - lec/lec-23a-biquads.qmd
        - lec/references.qmd
    # - part: Labor
    #   chapters:
    #     - lab/Experiment_01.qmd
    #     - lab/Experiment_02_TZ.qmd
    #     - lab/Experiment_03_TZ.qmd
          
bibliography: _bibliography/references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrbook 
    # lof: true
    # lot: true
    toc: true    
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    hyperrefoptions:
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"
    biblio-style: ieee
    highlight-style: github
    mainfont: "Calibri"
    # keep-tex: true
    output-file: ans
  epub:
    theme: flatly
    output-file: ans
  
execute:
  freeze: auto
