# Kapitel 9Dominant Pole ApproximationZero-Value Time Constant Analysis

# Motivation



* Last lecture we saw that the Miller approximation is a very useful tool that allows us to estimate the \-3dB bandwidth of our CS stage quickly and intuitively
  * Wouldn’t it be nice to have a similar technique of this kind that works for a broader class of circuits?
* The zero\-value time constant \(ZVTC\) method is a tool that meets this demand
* We will continue to use the CS amplifier example to illustrate this method\, along with its mathematical underpinnings


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Analysis Revisited (1)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.



* We know that
  * The transfer function of our circuit has a dominant pole that sets the \-3dB bandwidth
  * The non\-dominant pole and zero have little influence on the \-3dB bandwidth of the circuit
* Can we somehow use this fact to simplify the analysis?
  * Without circuit\-specific “tricks” like the Miller approximation


Non\-dominant pole\(s\) and zero\(s\)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Dominant Pole Approximation (1)

If our goal is to estimate the \-3dB frequency only\, we can discard the zero and write

Next\, use the fact that |p2|>>|p1| \, where p2 is the non\-dominant pole and p1 is the dominant pole that sets the \-3dB frequency

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

We can now compare to the original expression to find

This means that in order to estimate the \-3dB bandwidth of the circuit\, all we need to know is b1\!

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Zero-Value Time Constant Analysis



* A step\-by\-step circuit analysis method that allows us to determine b1 \(and only b1\) without solving for the complete transfer function\!
* Here's how it works
  * Remove all but one capacitor \(Cj\)
  * Short independent voltage sources
  * Remove independent current sources
  * Calculate resistance seen by capacitor \(Rj\) and compute
  * Repeat above steps for all remaining capacitors in the circuit
  * The sum of all     is equal to b1


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Example (1)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Example (2)



* A little more tricky\, but any linear circuit method will do
  * E\.g\. apply test current \(it\)\, write expression for vt\, find R=vt/it


“sum \+ product x gm”

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Example (3)

Step 4: Add up all time constants

Step 5: Compute estimate of \-3dB frequency

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Important Notes on ZVTC (1)



* The key advantages of this method are
  * It provides an excellent shortcut  for finding the \-3dB frequency of a circuit
  * In addition\, the method provides us with insight about the limiting time constants in our circuit\!
* Whenever you apply the ZVTC method\, it is important to remember the assumptions for which it is  _accurate_
  * The circuit has a dominant pole
  * The circuit does not have any zeros in the vicinity of its \-3dB frequency
* The time constants computed in the ZVTC method do not correspond to poles\!
  * Remember that the sum of the time constants is equal to b1


Quelle: EE114\, B\. Murmann\, Stanford Univ\.



* When the underlying assumptions are not precisely met\, it may still be “OK” to work with ZVTC
  * Provided that you clearly understand what you are doing…
* Example 1: AC coupling caps or bypass caps
  * Meant to be “shorts” at high frequencies\, and do not degrade the signal bandwidth
  * Typically OK to discard these caps to find the “upper corner frequency” of the circuit
* Example 2: Multiple poles of similar \(or same\) magnitude
  * See next page


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

