# Lecture 6Intrinsic CapacitanceBandwidth-Supply Current Tradeoff

Copyright © 2013 by Boris Murmann\, Stanford University

Copyright © 2018 by Mirco Meiners\, HSB

# CS Amplifier Revisited



* Interesting question
  * How fast can this circuit go?
* Ri models finite resistance in the driving circuit
  * Needed for a realistic discussion


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Circuit Speed



* There are two perspectives on “how fast” a circuit can go
  * Somewhat dependent on the application which one of the two matters more
* Time domain
  * Apply a transient at the input \(e\.g\. a voltage step\)\, measure how fast the output settles
* Frequency domain
  * Apply a sinusoid at the input\, measure the gain and phase of the circuit transfer function across frequency
* Knowing the time domain response\, we can estimate the frequency domain response\, and vice versa
* In ANS we will mostly work with frequency domain analyses to argue about the useful frequency range of a circuit


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Application Perspective



* Frequency ranges for various applications
  * Audio ~20Hz to 20kHz
  * Video signals ~50MHz
  * Cable TV ~100\-800MHz
  * Radios
    * AM ~500kHz–1700kHz
    * FM ~100MHz
    * Wireless LAN ~2\.4GHz or 5GHz
    * Cellular phones ~1GHz
    * GPS ~1227 and 1575 MHz
  * …


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# The Culprit



* In practical circuits\, the presence of capacitance prevents us from building circuits that can run “infinitely” fast
  * Sometimes inductors can be used improve the situation
* Intuition
  * High frequency results in large dvC/dt and large iC
  * Capacitor becomes a “short” for high frequencies


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# RC Low-pass

Laplace domain\(ignoring initial condition\)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Magnitude and Phase



* Evaluate H\(s\) for s=jω
  * Steady\-state phasor analysis
* Magnitude and phase of the transfer function are commonly illustrated using Bode plots
  * Simply a log\-log plot of the magnitude along with a log\-angle plot for the phase


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Bode Plot

At ω = 1/RC = |p|:

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Zeros

Many circuit transfer functions also contain zeros

In most cases that we are interested in\, zeros occur beyond the dominant pole frequencies and can intuitively be related to “some” mechanism preventing further transfer function roll\-off

A simple example

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Bode Plot

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Modeling MOSFET Capacitance (1)



* To predict the frequency response of our CS amplifier\, we need to understand the capacitances associated with the MOS device
* We will first look at "intrinsic gate capacitance"
  * Intrinsic means that this capacitance is unavoidable and required for the operation of the device
* There are plenty of “extrinsic” capacitances as well
  * We'll neglect these for the time being and discuss them in detail next lecture
* To model gate capacitance\, we must distinguish the MOSFET’s operating regions
  * Transistor on
    * Triode and active regions
  * Transistor "off"
    * Sub\-threshold operation


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Transistor in Triode Region

Electrons respond to gate via the S and D; this effectively “short out” the effects of CCB



* Gate terminal and conductive channel form a parallel plate capacitor across gate oxide CGC= WLεox/tox= WLCox
  * We can approximately model this using lumped capacitors of size ½ CGC each from gate\-source and gate\-drain
    * Changing either voltage will change the channel charge
* The depletion capacitance CCB adds extra capacitance from drain and source to substrate
  * Usually negligible \(see above comment\)


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Transistor in Saturation Region



* Assuming a long channel model\, if we change the source voltage
  * The voltage difference between the gate and channel at the drain end remains at Vt\, but the voltage at the source end changes
  * This means that the "bottom plate" of the capacitor does not change uniformly
* Detailed analysis shows that in this <span style="color:#ff3f3f"> </span> case Cgs=2/3WLCox
  * For your weekend amusement you can derive this; write Q\(V\(y\)\) and integrate 0L
* In the long channel model for active operation\, the drain voltage does not affect the channel charge
  * This means Cgd=0 in the saturation region\!
    * Neglecting second order effects and extrinsic caps\, of course


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Transistor Off



* There is no conductive channel
  * Gate sees a capacitor to substrate\, equivalent to the series combination of the gate oxide capacitor and the depletion capacitance
* If the gate voltage is taken negative\, the depletion region shrinks\, and the gate\-substrate capacitance grows
  * With large negative bias\, the capacitance approaches CGC


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Intrinsic MOS Capacitor Summary

|  | __Subthreshold__ | __Triode__ | __Saturation__ |
| :-: | :-: | :-: | :-: |
| __C__  __gs__ | 0 | ½ WLCox | 2/3 WLCox |
| __C__  __gd__ | 0 | ½ WLCox | 0 |
| __C__  __gb__ |  | 0 | 0 |

xd is the width of the depletion region at the silicon surface

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# CS Amplifier Revisited



* Assuming that the transistor operates in the saturation region\, we can construct the following small\-signal model
  * Important to note that we are still neglecting extrinsic capacitances here


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Example

Given: VB=2\.5V\, IB=500μA\, W/L=20/1\, R=5kΩ\, Ri=50kΩ

Technology data: μCox=90μA/V2\, VTn=0\.48V\, λ=0\.035V\-1\, Cox=4\.6fF/μm2

Calculate: VI \(such that ID=IB\, VO=VB\)\, Cgs\, f\-3dB

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Bode Plot from .ac Simulation

f\-3dB = 103\.6MHz

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Performance Considerations (1)



* Suppose we want to maximize the bandwidth of our circuit
  * And keep the current consumption \(ID\) as low as possible
* Further assume that Ri\, R and Av0 are fixed
  * Fixed by the particular application in which the circuit is used
* For the bandwidth\, we can write


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

For the current we can write



* Observations
  * Larger VOV means larger bandwidth
  * Unfortunately larger VOV also results in larger ID
* Part of your job as an analog designer is to choose VOV such that you get sufficient bandwidth while using as little current as possible


Quelle: EE114\, B\. Murmann\, Stanford Univ\.



* Even though we've come to this observation using a very simple example\, this tradeoff tends to hold in general
  * Of course\, additional considerations and second order dependencies will factor in as you learn more about analog circuit design…
* The reasons behind this tradeoff lie in the fundamental properties of the transistor itself
* To see this\, think about what we really want from the MOSFET
  * Large gm without investing much current
    * I\.e\. large gm/ID
  * Large gm without having large Cgs
    * I\.e\. large gm/Cgs


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# gm/ID and gm/Cgs

|  | VOV small | VOV large |
| :-: | :-: | :-: |
| gm/ID | Large | Small |
| gm/Cgs | Small | Large |

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Product

In cases where we want to get the "best of both worlds"\, it is interesting to look at the product of our two figures of merit



* While this result looks boring\, it shows that using smaller channel lengths improves circuit performance
  * Either or both speed and current efficiency


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Scaling Impact



* Thanks to "Moore's Law" feature sizes and thus the available minimum channel length has been shrinking continuously
  * Lmin has decreased roughly 2x every 5 years
  * Lmin=10μm in 1970\, Lmin=45nm in 2007\, Lmin=25nm in 2013
* From the above discussion\, it is clear that we can exploit technology scaling in different ways
  * Build  _faster_  circuits \(higher gm/Cgs\)\, while keeping power efficiency constant \(gm/ID\)
    * E\.g\. A/D converter for a disk drive \- want to maximize bandwidth/throughput
  * Build more  _efficient_  circuits \(higher gm/ID\)\, while keeping the bandwidth constant \(gm/Cgs\)
    * E\.g\. A/D converter for video signals \- bandwidth fixed by a certain standard


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Aside: gm/ID of a “Real Transistor”

Long channel predication \(2/VOV\) is fairly close to “real device” for VOV > 150mV

Unfortunately gm/ID does not approach infinity for VOV  0

Limit VOV >= 150mV in ANS to avoid non\-physical design outcomes

<span style="color:#008000">More Advanced Classes in Design</span>

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Aside: Transit Frequency (ωT)

The transit frequency of a transistor has "historically" been defined as the frequency where the magnitude of the common source current gain \(|io/ii|\) falls to unity

Ignoring extrinsic capacitance\, it follows that

Incidentally\, this metric is identical to the figure of merit we considered on the previous slides

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Aside: ωT Interpretation



* The transit frequency is only useful as a figure of merit in the sense that it quantifies gm/Cgs
* It does not accurately predict up to which frequency you can use the device
  * At high frequencies\, many assumptions in our "lumped" transistor model become invalid
  * Rule of thumb: lumped model is good up to about ωT/5
* At higher frequencies\, device modeling becomes more challenging and many effects depend on how exactly you layout and connect the device
  * These effects are covered in more detail in master courses or projects


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

