# Lecture 4Operation Point AnalysisInner workings of SPICE?

# Operating Point Calculations



* Calculating the operating point in the amplifier example from last lecture was relatively straightforward
  * Assume transistor operates in saturation region
  * Compute drain current \(via a simple closed form expression\)
  * Check if result is consistent with assumption \(VDS>VGS\-Vt\)
    * If not\, repeat calculation with triode equation
* Computing the operating point in general\, and in more complex circuits can be difficult
  * Primarily due to the transistors’ nonlinear I\-V characteristics and because their region of operation is not known a priori
* To give you a better feel for this issue\, we will work through a slightly more complex circuit
  * And take a look at how Spice handles the calculation


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Example

Given: VI=2V\, W=20μm\, L=1μm\, R1=5kΩ\, R2=25kΩ\, VDD=5V

Device parameters: μCox=50mA/V2\, Vt=0\.5V

Calculate: ID

Note:

This circuit is called a “common source amplifier with source degeneration\.” In this lecture we will only analyze the DC operating point of this circuit\. You will take a closer look at its small\-signal transfer function in exercise 2\.

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Calculations (1)



* Step 1
  * Assume device is on and operates in saturation
* Step 2
  * Solve for ID


Quelle: EE114\, B\. Murmann\, Stanford Univ\.



* Step 3
  * Plug in numbers
* Step 4
  * Compute VGS


Quelle: EE114\, B\. Murmann\, Stanford Univ\.



* Step 5
  * Check saturation assumption
* Step 6
  * Get angry\, because device operates in triode region\!
  * Go back to step 1 and use triode I\-V equation to find correct answer
    * You will do this as an exercise in homework 2…


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# How does Spice get This Answer?



* Building a tool that symbolically solves equations and plugs in numbers would be very difficult
  * More complex circuits may not even have closed form solutions
* Spice uses numerical methods applied to a linearized copy of the circuit to find the circuit’s operating point \(\.op\)
  * Let’s have a look at how this works…


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

Min\. Conductances

\(added for numerical reasons\)

# Linearized MOSFET Model Used in Spice

Non\-linear Equations

Linearized Equivalent

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# MOSFET I-V and Linearization

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

Set Min \(default\)

Conductances

# Linearized Model Calculations (1)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Analysis with Linearized Model

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Matrix Solution for VD and VS

Determine  _new_  VGS\, VDS

Re\-compute  _new_  \(linearized\) parameters

Re\-assemble matrix

Solve  _next iteration_  for voltages

<span style="color:#ff3f3f"> Stop</span>  when difference between iterations is less than  _specified tolerance_

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Convergence Issues



* Convergence may not always occur\, especially for large circuits with many nonlinear elements and feedback loops
  * Not a real problem any more in modern simulators
  * Today’s tools can properly handle \.op analyses for very large circuits \(>10\,000 devices\)
* A more common reason for non\-convergence is human error\, i\.e\. a bad netlist and or improper settings
  * Do not start by blaming the tool when your circuit does not converge; chances are that YOU have made a mistake…


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Small-Signal Circuit

Once iterations have converged\, the small\-signal parameters of the circuit are determined

Small\-signal response \(using \.ac\) boils down to solving a linear system of equations

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Other Analyses



* \.dc
  * Simply a series of \.op analyses for different inputs
  * All capacitors are open circuits \(inductors are shorts\)
* \.tran
  * Based on initial state of circuit \(\.op output\) Spice runs nodal analysis using numerical integration to track stimulus
  * All capacitors \(and inductors\) are taken into account
* For more information see
  * http://www\.ecircuitcenter\.com/AboutSPICE\.htm
  * http://www\.ecircuitcenter\.com/SpiceTopics/Overview/Overview\.htm
  * Kenneth S\. Kundert\, Designer's Guide to SPICE and Spectre®\, Springer\, 1995
    * Very good material on resolving convergence issues


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

