# Lecture 5Gain and Biasing ConsiderationsFinite Output Resistance

# CS Amplifier Revisited



* Interesting question
  * How much voltage gain can we get from this circuit?


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Upper Bound on Gain (1)

Plug in expression for gm

For operation in the saturation region\, we definitely require

Therefore\, we have



* This is an upper bound only\, useful for back of the envelope calculations \(and job interviews\)
  * Important to note that this expression does not hold with equality


Quelle: EE114\, B\. Murmann\, Stanford Univ\.



* The above derived upper bound comes for the fact that both gain and bias point depend on R
  * Want large R for large gain
  * Want small R to prevent device from entering triode region
* The upper bound may not be a serious issue in some circuits
  * Nonetheless it is interesting and insightful to think about ways around the issue
* We’ll do this graphically using “load line” plots


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Construction of Load Line Plot

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Putting Things Together

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Larger Resistance

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Discussion



* The issue with this configuration is that the load line is pinned to the point \(VDD\, 0\)
* Larger VDD allows use of larger R and therefore larger gain
  * This is also evident from the equation on slide 3
* It is possible to overcome this limitation by adding additional degrees of freedom; consider e\.g\. the following alternative load network


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Plot for IB = ID

Can increase R \(and gain\) without changing operating point

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# “Infinite” Gain?



* Tempting to think that we can now make R nearly “infinitely” large and get close to “infinite” gain
* This is not possible in practice for two reasons
  * Finite dId/dVgs of the transistor
    * More later
  * Sensitivity to mismatch between ID and IB will render the circuit impractical
    * We’ll look at this problem first


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Large R, ±10% Variation in IB

Operating point for \-10% IB change

Operating point for \+10% IB change

Ideal operating point

Very large changes in operating point \(VO\)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# A Closer Look

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Solutions



* Limit R to values such that expected mismatch in bias currents causes acceptable bias point variations; avoid “balancing marbles on the tip of a cone”
  * More on mismatch later in this course
* Feedback
  * Somehow sense VO and adjust IB \(or ID\) such that output sits at a proper operating point\, regardless of mismatch between ID and IB
  * More later in this course


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Intrinsic Gain

Suppose we manage to bias the circuit such that ID=IB precisely \(e\.g\. using feedback\) and let R∞



* In this case\, it turns out that the voltage gain of the circuit is still finite\, and equal to the so\-called “intrinsic gain” of the transistor
* Finite intrinsic gain is caused by the dependence of Id on Vds
  * Transistor in saturation is a very good current source\, but not an ideal one…


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Finite dId/dVds

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Modeling Finite dId/dVds



* In a modern short\-channel MOSFET several physical effects cause finite dID/dVDS
  * Channel length modulation \(CLM\)
  * DIBL\, SCBE\, …
  * The precise dependencies are very hard to model
    * Several pages of equations in a modern model such as BSIM4 and PSP
* In ANS\, we consider only channel length modulation through a first order treatment
* This will help us construct a manageable model that contains the relevant feature \(namely\, finite dId/dVds\) without going overboard with device physics


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Channel Length Modulation (1)



* Increasing VDS causes the depletion region around the drain to widen \(basic PN junction physics\)
* This pushes the pinch\-off point further away from the drain\, resulting in an effective shortening of the channel
  * Modeled as ΔL\(VDS\)


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Lamdba



* Single parameter that models finite dId/dVgs assuming linear VDS dependence
* Inversely proportional to channel length \(see equation on previous slide\)
* VERY IMPORTANT
  * λ is a “fudge factor” that helps us take finite dId/dVds into account to reason about the achievable small signal gain
  * Never\, ever\, rely on a specific\, precise value of lambda to establish a circuit’s operating point
    * Rule of thumb: if your circuit won’t work if λ is varied by ±50%\, it is plain impractical


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Small Signal Perspective

Around the operating point\, finite dId/dVgs can be modeled as a conductance gds \(or resistance ro=1/gds\)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Small Signal Output Conductance



* Approximation in last step is OK for quick calculations and large L
  * This approximation overestimates gds


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# MOSFET Model With Finite gds

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# CS Amplifier Model With Finite gds

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

λ2   <     λ1

|VA2|  >   |VA1|

# A Note About “Early Voltage”



* “Early Voltage” \(VA\) is defined as 1/λ \(in Spice\)
  * Corresponds \(roughly\) to the extrapolated intercept of the transistor's output characteristic with the Vds axis
* The intrinsic gain expression\, in terms of Early Voltage has a nice “feel” to it \(V/V\) given approximately by 2VA/VOV


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Numbers



* For a minimum length device in an exemplary technology \(L=1μm\)
  * λ=0\.1V\-1\, VA=10V
  * At VOV=150mV    gmro≅2VA/VOV=133\.33
* Suppose we want to build a common source stage with a voltage gain of 5 \(see example of lecture 3\)
  * Does finite ro matter? No\, we can see this without even calculating ro by comparing the desired gain to typical intrinsic gain values


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# When do we care about gmro?



* Op\-amp based feedback circuits
  * Precision in feedback circuits relies on building very high gain amplifiers
* Reference circuits
  * E\.g\. current references or current mirrors
  * Want to make current independent on voltage\, which relies on large ro
* More later…


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

