# Lecture 17Fundamentals of FeedbackStability and Return Ratio

# Stability



* Most general criterion: BIBO
  * Bounded input – bounded output
  * Applies to any system
* A continuous time linear system is BIBO stable if all its poles are in the left half of the s\-plane
  * Can calculate roots of 1\+T\(s\) to check stability
    * Tedious and hard to do in general\, but…


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Methoden für die Stabilitätskontrolle

Nyquist KriteriumEvaluation der offenen Kette T\(s\) in polarer Darstellung

Quelle: EE114\, B\. Murmann\, Stanford Univ\.Quelle: Regelungstechnik 1\, J\. Lunze

# Bode Criterion



* A subset of the general Nyquist criterion that can be applied when T\(s\) itself is stable
  * Safe to use in most electronic circuits
  * Beware of exceptions
* System is unstable when |T\(jω\)| > 1 at the frequency where Phase\(T\(jω\)\) = \-180°
* Can use simple bode plot to check for stability


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Bode Plot / Stability Measures

Typically want GM ≥ 3…5

Typically want PM ≥ 60…70°

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Closed Loop Peaking

Closed\-loop gain\, normalized to 1/f

\[Gray et al\, p\.632\]

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Solutions



* If all we needed was the closed loop transfer function\, we could simply do a  <span style="color:#cc0000">KCL/KVL based analysis</span>
  * Can be quite tedious\, especially for more complex circuits
  * Hard to assess stability and stability margin
* <span style="color:#cc0000">Two port feedback analysis</span>
  * "Shunt\-series\, shunt\-shunt\, series\-shunt\, series\-series" feedback configurations
  * Attempts to identify amplifier \(a\) and feedback network \(f\) with loading effects included
  * Elegant approach with lots of neat theory and examples\, but …
  * Some feedback circuits cannot be modeled using two\-ports
    * E\.g\. bias circuits with feedback loops tend to have only one port


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# A Warm-up Example

Hard to de\-couple a\(s\) and f\(s\)\, especially given finite gain and nature of MOS impedance\.

A quick word about  _biasing_ :

Current\-source biasing in this circuit doesn’t work without feedback \(to set the drain voltage\)

Namely\, the resistive feedback constrains the  _gate and drain voltages to be equal_

Let’s do the exact \(nodal\) analysis\!

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Exact (nodal) Analysis

Solving eq\. \(2\) for vx=f\(vout\)\, then substituting this result into eq\. \(1\) for vx:

If the gmR terms are much greater than 1\, the result agrees with our OpAmp solution

\(re\-ordered eq\. \(1\)\)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Alternate Feedback Model

_Motivation_ :

Terms all directly computable and measurable \(with SPICE\)

Removes the issues of idealization \(not real in practical MOS circuits\)

Derivation: see Gray et al\. p\. 601\-4

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Return Ratio Analysis (1)



* Does not attempt to identify forward gain and feedback network transfer functions separately
* Analysis aims to identify gain around feedback loop
  * Loop gain\, loop transmission\, a·f
    * Different terminology for the same thing
* From the loop gain of a circuit\, we can determine
  * Stability\, closed loop gain characteristics\, node impedances
* Analysis can be applied to arbitrary feedback circuits\, independent of topology\, port structure\, etc\.
* We will first look at the complete framework of this technique
  * Then identify a way to partition the analysis for our needs and reduce its algebraic overhead


Quelle: EE114\, B\. Murmann\, Stanford Univ\.



* Set all independent sources to zero
* Identify a  _controlled source_  in the feedback loop that you want to analyze and break the loop by disconnecting the source
  * E\.g\. VCCS\, VCVS\, …
* Inject a test signal st at the breakpoint
  * Current or voltage\, depending on type of removed source
* Find the return signal sr generated by the controlled source that was disconnected from the circuit in step 2\.
* The  _return ratio_  of the controlled source is given by  <span style="color:#cc0000">RR = –</span>  <span style="color:#cc0000">s</span>  <span style="color:#cc0000">r</span>  <span style="color:#cc0000">/</span>  <span style="color:#cc0000">s</span>  <span style="color:#cc0000">t</span>
  * _Provided that_  we have chosen a controlled source that breaks the loop under consideration \(and no other loop\)\, the return ratio of the source is equal to the loop gain of the circuit\, i\.e\. RR = T
  * Comment: we must have T \(not just any RR\) for the stability analysis


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Example Continued - RR Calculation

Starting with very low frequency: \(I\.e\. we’ll ignore Cgs effects\)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Other Terms in FB Model

A is defined as the transfer function when the gain element becomes infinite\.

The input \(vgs\) node must be zero\, therefore:

vin/R1= \- vout/R2

vout/vin=  <span style="color:#cc0000"> __\- R__ </span>  <span style="color:#cc0000"> __2__ </span>  <span style="color:#cc0000"> __/R__ </span>  <span style="color:#cc0000"> __1__ </span>

<span style="color:#cc0000"> __“__ </span>  <span style="color:#cc0000"> __d__ </span>  <span style="color:#cc0000"> __”__ </span>  is defined as the transfer function when the gain element becomes zero\.

In the above example\, if the gm generator has no effect \(zero\)\, the transfer function is  <span style="color:#cc0000"> __unity \(1\)__ </span>  since there is no attenuation between input and output\.

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Final Gain Expression

Does this make sense?

Look at asymptotes as gm0 and gm∞

Answer: we do get correct limiting solutions

And…it does reduce to the EXACT \(nodal\) solution

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

Does this make sense?

Look at asymptotes as gm0 and gm∞

Answer: we do get correct limiting solutions

And…it does reduce to the EXACT \(nodal\) solution

Now\, let’s look at a slightly more complicated example\, considering the RR and it’s implications on bias circuit stability\.

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

\[Lee\, 2nd ed\. p\.326\]

# ΔVGS Reference

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Where to insert it?

The feedback must be  _global_ \, not impacted by other feedback loops\.

M2 has R2 degeneration\, which amounts to another feedback loop

M1 and M4 are diode\-connected; the transconductance elements do not break the main loop

M3 is the only “normal” CS gain stage

_General_  comment:  RR of CG\, CD or degenerated CS cannot be used to find the loop gain of a circuit

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Unrolling and Linearizing

<span style="color:#cc0000">Red\-</span> circuit features that make st insertion not work;  <span style="color:#0000ff">Blue\-</span> best place for st insertion

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Computing Return Ration (RR)

putting the pieces together…

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Does RR make sense?

The loop has two inverting gain blocks\, each loaded with a “diode\-connected” MOS device\.

The resulting return ratio is  _negative_  \(I\.e\. it’s definitely not negative feedback\, even at zero frequency ac\)\.

The challenge is to keep the magnitude of the RR \(=T\) less than unity \(1\)\.

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# What about the numbers?

For  <span style="color:#cc0000">m=2</span> : VOV2=141mV; R2=586Ω

If gm4=gm3=gm1=1x10\-3 S

Assume I\(M3\)=I\(M4\)=IREFN= <span style="color:#cc0000">100</span>  <span style="color:#cc0000">μ</span>  <span style="color:#cc0000">A</span> \, VOV1= <span style="color:#cc0000">200mV</span>

Recall \(Lect\. 14\, p\.8\):

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Possible problems?

If C shorts out R2\, RR increases \(which is not good\!\)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Appendix Feedback and Port Impedances

# Using Feedback to Modify Port Impedances



* Feedback can be used to increase/decrease port impedances
  * In fact\, we have already seen an example of such behavior \(Lecture 19\, slide 7\)
    * Closed loop bandwidth of feedback amplifier can be \(1\+T\) higher than open loop bandwidth
    * This means the impedance seen by the load capacitor must drop in the presence of feedback
* We can calculate the port impedances of arbitrary feedback circuits using "Blackman's Impedance Formula"
  * Based on loop gain calculations \(RR…doesn’t have to be T\)
  * Extremely useful and easy to use


Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Blackman's Impedance Formula



* First\, find port impedance with feedback loop broken
  * E\.g\. set gm=0 \(k=0 in model; can also be av\-\-see examples\)
* Calculate loop gain in circuit with port under consideration  _shorted_
* Calculate loop gain in circuit with port under consideration  _open_
* In many cases\, either the "shorted" or "open" loop gain is zero


First\, let’s quickly review a couple of aspects of the RR methodology

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

Rest of feedback amplifier

# Reminder about RR Formulation

Careful manipulations gives overall transfer function:

Various terms defined as follows:

Terms as discussed on p\. 10 ff\.

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

Rest of feedback amplifier

# Closed-Loop Impedances with RR

Next\, compute RR for two cases of k:

Port X  _open_  \( <span style="color:#cc0000">i</span>  <span style="color:#cc0000">x</span>  <span style="color:#cc0000">=0</span> \)

Port X  _shorted_  \( <span style="color:#cc0000">v</span>  <span style="color:#cc0000">x</span>  <span style="color:#cc0000">=0</span> \)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Example 1: Bootstrapped Source Follower

This node follows vt \(ideal source follower\)

_Note_ : k=av also\, RR=T

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Example 2: Super Source Follower

We can use either gm2 or gm1 to get RR

Here we use gm2 as “k”

Details of T\(output open\):

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Details, Example 2

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Example 3: Shunt-Shunt Stage

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

_Note_ : k=av also\, RR=T

# Example 4: Active Cascode

Also referred to as "Regulated Cascode" or "Gain Boosting" technique

av=0  gate M2 grounded:

\(test signal cannot change vx hence there is no signal at vi\)

\(with M2 drain grounded \(CD\) and neglecting ro terms w\.r\.t\. the 1/gm terms\, the voltage\-follower expression is then multiplied by av\)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

\(test signal cannot change vg2\)

# Details, Example 4

gm\-generated current flows in loop\, changing drain voltage\, but vx=0

\(with M2  _drain grounded_  \(CD\) and neglecting ro terms w\.r\.t\. the  <span style="color:#cc0000">1/g</span>  <span style="color:#cc0000">m</span>  <span style="color:#cc0000"> </span> terms\, the voltage\-follower expression is then multiplied by av\)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Example 5: ZVTC Calculations

Remember Problem 3 of the midterm?

Let’s look at this again\, with RR perspective

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Example 5: ZVTC Impedance

_Side Comment_ : Zin here is infinite \(ignoring ro\)

Let’s have a look at Blackman:

Rin \(k=0\)=Ri \+ RG

RR\(short\)=0

RR\(open\)=gmRi

\(short kills gm generator\)

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

# Details, RR for ZVTC

Quelle: EE114\, B\. Murmann\, Stanford Univ\.

